# Generated by Django 2.2.1 on 2019-05-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default=None, max_length=255, verbose_name='Supplier')),
                ('buying_price', models.FloatField(default=None, verbose_name='Buying Price')),
                ('selling_price', models.FloatField(default=None, verbose_name='Selling Price')),
                ('units_bought', models.IntegerField(default=None, verbose_name='Units Purchased')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Restock',
                'verbose_name_plural': 'Restock',
            },
        ),
    ]
