# Generated by Django 2.2.1 on 2019-05-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_restock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
